### ISSUE TITLE
Tracking issue for cleaning-up allocations

### ISSUE THREAD

**Issue by timotree3** [holochain/holochain-rust#1733]
The current code-base does a lot of unnecessary allocations. Here are some examples of common things in the code-base that cause allocation:

- `format!`
- `.to_string()`
- `.clone()`
- `.collect()`
- `.to_path_buf()`
- `.to_string_lossy()`
- `.into_vec()`

This issue is intended to classify the different patterns in the code-base that allocate unnecessarily and track the progress in cleaning them up.

- [ ] Calling functions that take `&String`s (in progress: #1732)
- [ ] Calling functions that take `&PathBuf` (in progress: #1701)
- [ ] Converting between strings and paths (in progress: #1701)
- [ ] Calling `format!` only to use the result as a format argument
- [ ] Taking things by reference just to immediately clone them
- [ ] Allocating `PathBuf`s only to `join` them
- [ ] Calling `.collect()` only to iterate over the result
- [ ] Calling `.to_string()` only to use the result for comparison
- [ ] Converting `String`s to `JsonString`s
- [ ] Returning `String` errors
- [ ] Storing owned collections in a struct when giving the struct a lifetime and storing references would do

Feel free to check these boxes or add more to-dos if any come up! I believe maintainers are able to edit this post.

**Comment by timotree3** [comment]
As I've started to do with these two "roundup" PRs. I intend to slowly check off each box on this list.

**Comment by thedavidmeister** [comment]
sounds good :)

my request would be to keep PRs as easy to review and focussed as possible

**Comment by timotree3** [comment]
I'm totally with you! :-) I've been making a serious effort to do just that.

I've been going for the strategy of each commit having one well explained transformation, applied across the code base. The only other option that I've thought of is to apply all the transformations to a single module and then make a PR for each module. 

Is there some approach that you have in mind?

**Comment by thedavidmeister** [comment]
@timotree3 nothing specific, just keep it as easy to review as possible :)
