### ISSUE TITLE
port all chain.go functionality and tests

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#29]
## Checklist

A checklist to keep track of the `chain.go` basic port to the `source_chain` module:

- [x] a concept of a "chain" of headers and entries
  - implemented as `source_chain::Pair`
- [ ] chains can be saved/loaded from the file system #231 
- [ ] headers and entries use the correct hashing algo #20 
- [x] headers and entries reference each other by hash
  - implemented as `common::entry::Entry` and `common::entry::Header`
- [x] helper fn `top` to get top header (most recently added)
- [ ] helper fn `nth` to get nth most recently added header
- [x] helper fn `TopType` to get most recently added header of given type
- [ ] ability to provide an entry + key and have it appended with correct headers + signatures
- [x] helper fn `get` to lookup header by hash: #30
- [x] helper fn `getEntry` to lookup entry by entry hash: #30
- [x] helper fn `getEntryHeader` to lookup header by entry hash: #30
  - this should be merged with `getEntry` if all lookups return pairs
- [x] ability to serialize/deserialize a chain: #61
- [ ] ability to "dump" a chain to a string
- [x] ability to walk a chain from most recent to least recent
  - implemented move and ref `for` loop as `chain.iter()`, `(&chain).into_iter()` and `chain.into_iter()`
- [x] ability to validate a chain: #31  
- [x] ability to JSON stringify a chain #61 
- [ ] ability to graphvis a chain
- [ ] helper fn `Length` to get the number of entries in a chain
- [ ] helper fn `BundleStarted` to get the start index of the active bundle
- [ ] ability to start/close bundles

## Diff

summary of major differences planned/implemented between the go/rust versions:

- multiple implementations of the source chain trait, so memory/file/db chains can all be independently maintained
- dump/JSON/graphvis functionality will all come under the serialize/deserialize banner
- rust chains:
  - append entries (internally generating headers/pairs)
  - return pairs
  - perform direct lookups by hash
  - prefer composable iteration methods/traits over ad-hoc DSL (e.g.`filter` vs. `TopType` 😬 )
  - leverage immutability much more

## Ongoing

things that will likely come up again in the future, that are not solved in the go version currently.

- source chains that support concurrency
