### ISSUE TITLE
MDBOOK QA checklist

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-rust#343]
- [ ] add links in and between everything possible
- [ ] ensure all links are valid
- [ ] add licensing information
- [ ] add links to pages to feedback forms and how to contribute
